// The Pythagorean theorem states that the sum of two squares of the sides of a right triangle is equal to the square of the hypotenuse. For example, if two sides of a right triangle have lengths of 3 and 4, then the hypotenuse must have the length of 5. Together the integers 3, 4 and 5 form a *Pythagorean triple*. There are an infinite number of such triples. Given two positive integers, `m` and `n` where `m > n`, a Pythagorean triple can be generated by the following formulas:
// `side1 = m^2 - n^2`
// `side2 = 2mn`
// `hypotenuse = m^2 + n^2`
// The triple (side1 = 3, side2 = 4, and hypotenuse = 5) is generated by this formula when `m = 2` and `n = 1`. Write a program that takes values fot m and n as input and displays the values of the Pythagorean triple generated by the formulas above.
#include <stdio.h>

int main(void) {
    int m, n, t,
        side1, side2, hypotenuse;
    
    // Takes input
    printf("Please input two integers for the formula: "); scanf(" %d %d", &m, &n);
    
    // Assures m is larger than or equal to n
    (m < n) ? t = m, m = n, n = t : 0;

    // Calculates formula
    side1 = m*m - n*n;
    side2 = 2*m*n;
    hypotenuse = m*m + n*n;

    // Prints result
    printf("First cathesus: %d\nSecond cathesus: %d\nHypotenuse: %d", side1, side2, hypotenuse);

    return 0;
}